services:
  web:
    build: .
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=${USER}_dev
      - OTEL_SERVICE_NAME=${USER}-tracing-app
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  otelcol:
    image: quay.io/signalfx/splunk-otel-collector:0.26.0
    environment:
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}
      - SPLUNK_BALLAST_SIZE_MIB=220
    ports:
      - "4317:4317"