services:
  web:
    build: .
    ports:
      - "5000:5000"
  otelcol:
    image: quay.io/signalfx/splunk-otel-collector:latest
    environment:
      - SPLUNK_ACCESS_TOKEN
      - SPLUNK_REALM
      - SPLUNK_BALLAST_SIZE_MIB=683
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "55678-55680:55678-55680"
      - "6060:6060"
      - "7276:7276"
      - "8888:8888"
      - "9411:9411"
      - "9943:9943"