services:
  web:
    build: .
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=environment=${USER}_dev
      - OTEL_SERVICE_NAME=${USER}-tracing-app
      - SPLUNK_SERVICE_NAME=${USER}-tracing-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  otelcol:
    image: quay.io/signalfx/splunk-otel-collector:0.22.0
    environment:
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}
      - SPLUNK_BALLAST_SIZE_MIB=220
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "55678-55680:55678-55680"
      - "6060:6060"
      - "7276:7276"
      - "8888:8888"
      - "9411:9411"
      - "9943:9943"